# Generated by Django 3.2.7 on 2021-09-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_upvote_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upvote",
            old_name="upvote",
            new_name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
